### ISSUE TITLE
Doesn't show newly created namespaces.

### ISSUE THREAD

**Issue by madhu25** [ElasticBox/elastickube#89] opened 2016-06-09 10:53 UTC
When I create a new namespace, it doesn't show newly created namespaces. It only shows already deployed namespaces. Why?

**Comment by paulino-corujo** [comment] 2016-06-09 14:34
@madhu25 can you post this info?:
- Browser and version the issue is happening on
- Is it happening when you create a namespace using ElasticKube or when you manually create a new namespace in Kubernetes.
- Is there any error in the javascript log console?
- If you reload the ElasticKube application does it comes up?

**Comment by madhu25** [comment] 2016-06-13 15:50
- Chrome 
- It is happening both ways when I create namespace using ElasticKube and manually
- No error
- No it doesn't

**Comment by arnaud-elasticbox** [comment] 2016-06-14 20:25
@madhu25 thanks for reporting the issue. I was able to reproduce the issue and I have submitted a fix:
https://github.com/ElasticBox/elastickube/pull/95

**Comment by madhu25** [comment] 2016-06-15 09:38
Thanks :)

**Comment by arnaud-elasticbox** [comment] 2016-06-17 16:39
Pull request merged, closing it.

**Closed by arnaud-elasticbox** 2016-06-17 16:39 UTC
