### ISSUE TITLE
Failed to create elastickube-diagnostics

### ISSUE THREAD

**Issue by tujunxiong** [ElasticBox/elastickube#53] opened 2016-04-14 08:15 UTC
Hello,
My kube cluster was deployed by Azure script with 3 kube nodes, tried to use 
`curl -s https://elastickube.com | bash -s -- -u http://kube-00:8080`

to install elastickube and failed, error message is:

Failed to create docker container with error: no such image
spec.containers{elastickube-diagnostics}
Count:1051

Dashboard deployed and hope that can help:
http://13.76.246.110:9090/#/replicationcontrollers/kube-system/elastickube-server

I am new to Kubernetes and hope you can help me on this.

Thanks!

**Comment by davisein** [comment] 2016-04-14 09:58
Hi @tujunxiong,
It seems that there is a problem accessing dockerhub from your Kubernetes cluster. I'm not sure if you have it configured or not.
Could you log in into one of the nodes and execute (with enough permissions, sudo if needed):
docker pull elasticbox/elastickube-diagnostics

Does it work?
If it doesn't work please try:
docker pull registry.hub.docker.com/elasticbox/elastickube-diagnostics:latest

Currently, all our ElasticKube images are public in Docker Hub which is the most common docker registry so it's required to have access there.

**Comment by davisein** [comment] 2016-04-14 11:45
Hi @tujunxiong,

I have found the issue. We are publishing it but it was a wrong pull image policy in the default definition of the service and we didn't detect it because it was in the local cache.

You can just remove the line 'imagePullPolicy: Never' from the bash script to solve the issue:
```
curl -s https://elastickube.com | grep -v 'imagePullPolicy: Never' | bash -s -- -u http://kube-00:8080
```

We will publish the solution for everybody soon. Let me know if this works

**Comment by amarruedo** [comment] 2016-04-14 13:18
I was experiencing the same issue. I can confirm that running 

`curl -s https://elastickube.com | grep -v 'imagePullPolicy: Never' | bash -s -- -u http://kube-00:8080`

solves the problem.

**Comment by tujunxiong** [comment] 2016-04-14 13:27
@davisein Yes, now is working with this. Thanks!

**Comment by davisein** [comment] 2016-04-14 17:38
Hey @tujunxiong @amarruedo thanks for the feedback!

It's already fixed on the website so you don't need the grep -v anymore. I'm closing this.

Have fun with ElasticKube 😄

**Closed** 2016-04-29 17:40 UTC
